inventory/urls.py
from django.urls import path

from inventory import views

urlpatterns = [
    path('', views.ItemListView.as_view(), name='item-inventory'),
    path('sku/', views.SKUInventoryView.as_view(),
         name='inventory-sku'),
    path('items-inventory-location/', views.LocationInventoryView.as_view(),
         name='item-inventory-location'),
    path('<int:pk>/sku_detail/', views.SKUDetailView.as_view(), name='sku_detail'),

    path('<str:pk>/detail/', views.ItemDetailView.as_view(), name='item-detail'),

    # autocompletes
    path('autocomplete/skus/', views.SKUAutocomplete.as_view(), name='sku-autocomplete'),
    path('autocomplete/locations/', views.LocationAutocomplete.as_view(), name='location-autocomplete'),
    path('autocomplete/items', views.ItemAutocomplete.as_view(), name='item-autocomplete')
]

principal/urls.py
"""principal URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from iot import views as iot_views
from rfid import views as rfid_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', iot_views.DashboardView.as_view(), name='index'),

    # URLS LOGISTICS (Include rfid.urls)

    path('rfid/', include(('rfid.urls', 'rfid'), namespace='rfid')),
    path('inventory/', include(('inventory.urls', 'inventory'), namespace='inventory')),
    path('warehouse/', include(('warehouse.urls', 'warehouse'), namespace='warehouse')),
    path('reports/', include(('reports.urls', 'reports'), namespace='reports')),

    # REST API URL (Include rest_api.url)

    path('api/', include(('rest_api.urls', 'rest_api'), namespace='rest_api')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rfid/urls.py
"""RFID App Urls"""

from django.urls import path
from . import views as rfid_views

urlpatterns = [
    path('readers/', rfid_views.ReadersListView.as_view(), name='rfid-readers'),
    path('readings/', rfid_views.ReadingsListView.as_view(), name='rfid-readings')
]

warehouse/urls.py
from django.urls import path
from warehouse import views

urlpatterns = [
    path('transfer-orders/', views.TransferOrderListView.as_view(),
         name='transfer-order-list'),
    path('transfer-orders/create/', views.CreateTransferOrder.as_view(), name='create_transfer_order'),
    path('transfer-orders/<int:id_order>/detail/',
         views.TransferOrderDetailView.as_view(), name='transfer-order-detail'),
    path('entries/', views.WarehouseEntryListView.as_view(),
         name='warehouse-entry-list'),
    path('entries/<int:id_entry>/detail/',
         views.WarehouseEntryDetailView.as_view(), name='warehouse-entry-detail'),
    path('transfer-orders/tracking/', views.TrackingTransfersView.as_view(), name='tracking-transfer-orders'),
    path('tracking/', views.TrackingWarehouseView.as_view(), name='tracking-warehouse'),
]

templates/dashboard/logistics/logistics_index.html
{% extends "dashboard/dashboard_base.html" %}
{% load static %}

{% block child %}
<main class="c-main">
    <div class="container-fluid">
        <div class="fade-in">
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-accent-info">
                        <div class="card-header">
                            <span class="h2">Inventario <i class="fa fa-line-chart" aria-hidden="true"></i></span>
                            <a class="btn btn-outline-info float-right" href="{% url 'inventory:item-inventory' %}" role="button">Ver</a>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 col-sm-1">
                                    <div class="card overflow-hidden">
                                        <div class="card-body p-0 d-flex align-items-center">
                                            <div class="bg-gradient-dark p-2 mfe-2">
                                                <svg class="c-icon c-icon-xl">
                                                <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-qr-code"></use>
                                                </svg>
                                            </div>
                                            <div class="row">
                                                <div class="col-7 align-items-center">
                                                    <div class="text-muted text-uppercase font-weight-bold small">Total Unidades</div>
                                                </div>
                                                <div class="col-5 align-items-center">
                                                    <div class="text-value text-info">{{total_items}}</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-1">
                                    <div class="card overflow-hidden">
                                        <div class="card-body p-0 d-flex align-items-center">
                                            <div class="bg-gradient-dark p-2 mfe-2">
                                                <svg class="c-icon c-icon-xl">
                                                <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-folder"></use>
                                                </svg>
                                            </div>
                                            <div class="row">
                                                <div class="col-7 align-items-center">
                                                    <div class="text-muted text-uppercase font-weight-bold small">Total Referencias</div>
                                                </div>
                                                <div class="col-5">
                                                    <div class="text-value text-info">{{total_sku}}</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card card-accent-info">
                    <div class="card-header">
                        <span class="h2">Tracking <i class="fa fa-map-marker" aria-hidden="true"></i></span>
                        <a class="btn btn-outline-info float-right " href="{% url 'warehouse:tracking-transfer-orders' %}" role="button">Ver pedido</a>
                        <a class="btn btn-outline-info float-right mx-2" href="{% url 'warehouse:tracking-warehouse' %}" role="button">Ver bodega</a>
                    </div>
                    <div class="card-body">Texto por definir</div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card card-accent-info">
                        <div class="card-header">
                            <span class="h2">Entradas<i class="fa fa-arrow-circle-up" aria-hidden="true"></i></span>
                            <a class="btn btn-outline-info float-right" href="{% url 'warehouse:warehouse-entry-list' %}" role="button">Ver</a>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-6">
                                    <div class="card overflow-hidden">
                                        <div class="card-body p-0 d-flex align-items-center">
                                            <div class="bg-gradient-dark p-2 mfe-2">
                                                <svg class="c-icon c-icon-xl">
                                                <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-qr-code"></use>
                                                </svg>
                                            </div>
                                            <div class="row">
                                                <div class="col-7 align-items-center">
                                                    <div class="text-muted text-uppercase font-weight-bold small">Unidades Ingresadas</div>
                                                </div>
                                                <div class="col-5 aling-items-center">
                                                    <div class="text-value text-info">{{total_warehouseentries}}</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card card-accent-info">
                        <div class="card-header">
                            <span class="h2">Salidas <i class="fa fa-arrow-circle-down" aria-hidden="true"></i></span>
                            <a class="btn btn-outline-info float-right" href="{% url 'warehouse:transfer-order-list' %}" role="button">Ver</a>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-6">
                                    <div class="card overflow-hidden">
                                        <div class="card-body p-0 d-flex align-items-center">
                                            <div class="bg-gradient-success p-2 mfe-3">
                                                <svg class="c-icon c-icon-xl">
                                                <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-qr-code"></use>
                                                </svg>
                                            </div>
                                            <div class="row">
                                                <div class="col-7">
                                                    <div class="text-muted text-uppercase font-weight-bold small">Unidades enviadas</div>
                                                </div>
                                                <div class="col-5">
                                                    <div class="text-value text-info">{{total_transferitems}}</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="card overflow-hidden">
                                        <div class="card-body p-0 d-flex align-items-center">
                                            <div class="bg-gradient-warning p-2 mfe-3">
                                                <svg class="c-icon c-icon-xl">
                                                <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-av-timer"></use>
                                                </svg>
                                            </div>
                                            <div class="row">
                                                <div class="col-8">
                                                    <div class="text-muted text-uppercase font-weight-bold small">Salidas en alistamiento</div>
                                                </div>
                                                <div class="col=4">
                                                    <div class="text-value text-info">{{total_inprogress_orders}}</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            </div>
        </div>
  </div>
</main>
{% endblock %}