principal/urls.py
"""principal URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from iot import views as iot_views
from rfid import views as rfid_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', iot_views.DashboardView.as_view(), name='index'),

    # URLS LOGISTICS (Include rfid.urls)

    path('rfid/', include(('rfid.urls', 'rfid'), namespace='rfid')),
    path('inventory/', include(('inventory.urls', 'inventory'), namespace='inventory')),
    path('warehouse/', include(('warehouse.urls', 'warehouse'), namespace='warehouse')),
    path('reports/', include(('reports.urls', 'reports'), namespace='reports')),

    # REST API URL (Include rest_api.url)

    path('api/', include(('rest_api.urls', 'rest_api'), namespace='rest_api')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rfid/urls.py
"""RFID App Urls"""

from django.urls import path
from . import views as rfid_views

urlpatterns = [
    path('readers/', rfid_views.ReadersListView.as_view(), name='rfid-readers'),
    path('readings/', rfid_views.ReadingsListView.as_view(), name='rfid-readings')
]

warehouse/urls.py
from django.urls import path
from warehouse import views

urlpatterns = [
    path('transfer-orders/', views.TransferOrderListView.as_view(),
         name='transfer-order-list'),
    path('transfer-orders/create/', views.CreateTransferOrder.as_view(), name='create_transfer_order'),
    path('transfer-orders/<int:id_order>/detail/',
         views.TransferOrderDetailView.as_view(), name='transfer-order-detail'),
    path('entries/', views.WarehouseEntryListView.as_view(),
         name='warehouse-entry-list'),
    path('entries/<int:id_entry>/detail/',
         views.WarehouseEntryDetailView.as_view(), name='warehouse-entry-detail'),
    path('transfer-orders/tracking/', views.TrackingTransfersView.as_view(), name='tracking-transfer-orders'),
    path('tracking/', views.TrackingWarehouseView.as_view(), name='tracking-warehouse'),
]

rfid/models.py
"""RFID Models"""

from django.db import models
from inventory.models import Location, Position


class Node(models.Model):
    name = models.CharField(max_length=140)
    description = models.CharField(max_length=140, null=True, blank=True)
    location = models.ForeignKey(Location, on_delete=models.PROTECT)

    def __str__(self):
        return '{}-{}'.format(self.pk, self.location)

    class Meta:
        db_table = 'node'


class ReaderBrand(models.Model):
    name = models.CharField(max_length=140)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        db_table = 'reader_brand'


class Reader(models.Model):
    name = models.CharField(max_length=140)
    serial_number = models.CharField(max_length=140, unique=True)
    brand = models.OneToOneField(ReaderBrand, on_delete=models.PROTECT)

    def __str__(self):
        return '{}-[{}]'.format(self.brand, self.serial_number)

    class Meta:
        db_table = 'reader'


class ReaderAntenna(models.Model):
    name = models.CharField(max_length=140)
    serial_number = models.CharField(max_length=140, unique=True)
    reader = models.ForeignKey(Reader, on_delete=models.CASCADE)
    position = models.OneToOneField(
        Position, on_delete=models.DO_NOTHING, related_name='antennas',
        blank=True, null=True
    )

    def __str__(self):
        return '{}-[{}]'.format(self.name, self.name)

    class Meta:
        db_table = 'reader_antenna'


class Reading(models.Model):
    ACTION = (
        ('IN', 'Entrada'),
        ('OUT', 'Salida'),
        ('READ', 'Lectura')
    )
    id = models.BigAutoField(primary_key=True)
    epc = models.CharField(max_length=150)
    node = models.ForeignKey(Node, on_delete=models.PROTECT)
    reader = models.ForeignKey(Reader, null=True, on_delete=models.PROTECT)
    antenna = models.ForeignKey(ReaderAntenna, null=True, on_delete=models.PROTECT)
    timestamp_reading = models.DateTimeField(auto_now_add=True)
    action = models.CharField(max_length=10, choices=ACTION, default='READ')

    def __str__(self):
        return '{}-[{}]'.format(self.epc, self.reader)

    class Meta:
        db_table = 'reading'

warehouse/models.py
from django.db import models

from inventory.models import Location, Item
from rfid.models import Reading


class TransferOrder(models.Model):
    STATE = (
        ('RE', 'Solicitado'),
        ('IP', 'En Alistamiento'),
        ('IT', 'En Tránsito'),
        ('CO', 'Entregado')
    )
    destination = models.ForeignKey(Location, on_delete=models.PROTECT)
    expected_completion_date = models.DateField()
    actual_completion_date = models.DateTimeField(null=True, blank=True)
    state = models.CharField(max_length=3, choices=STATE, default='RE')

    def __str__(self):
        return '{}-[{}]'.format(self.pk, self.state)

    @property
    def total_skus(self):
        return TransferOrderItem.objects.filter(order=self).values('item__sku').distinct().count()

    @property
    def total_items(self):
        return TransferOrderItem.objects.filter(order=self).count()

    class Meta:
        db_table = 'transfer_order'


class TransferOrderItem(models.Model):
    STATE = (
        ('RE', 'Por alistar'),
        ('AL', 'Alistado'),
        ('NOE', 'No entregado'),
        ('EN', 'Entregado')
    )
    order: TransferOrder = models.ForeignKey(
        TransferOrder, on_delete=models.CASCADE, null=True
    )
    item: Item = models.OneToOneField(Item, on_delete=models.PROTECT)
    state = models.CharField(max_length=3, choices=STATE, default='RE')

    def __str__(self):
        return '{}-{}-[{}]'.format(self.item.display_name, self.item.epc, self.state)

    @property
    def last_out_reading(self):
        return Reading.objects.filter(
            epc=self.item.epc,
            action='OUT'
        ).order_by('-timestamp_reading').first()

    class Meta:
        db_table = 'transfer_order_item'
        unique_together = ('order', 'item')


class TransferOrderTracking(models.Model):
    order = models.ForeignKey(TransferOrder, on_delete=models.CASCADE, null=True)
    timestamp_reading = models.DateTimeField(auto_now_add=True)
    latitude = models.DecimalField(max_digits=10, decimal_places=7)
    longitude = models.DecimalField(max_digits=10, decimal_places=7)

    class Meta:
        db_table = 'transfer_order_tracking'


class WarehouseEntry(models.Model):
    entry_date = models.DateTimeField()
    origin = models.ForeignKey(Location, on_delete=models.PROTECT)
    location = models.ForeignKey(Location, on_delete=models.PROTECT, related_name='warehouse_entries')

    @property
    def total_skus(self):
        return WarehouseEntryItem.objects.filter(entry=self).values('item__sku').distinct().count()

    @property
    def total_items(self):
        return WarehouseEntryItem.objects.filter(entry=self).count()

    def __str__(self):
        return '{}-[{}]'.format(self.pk, self.origin)

    class Meta:
        db_table = 'warehouse_entry'


class WarehouseEntryItem(models.Model):
    entry = models.ForeignKey(WarehouseEntry, on_delete=models.PROTECT)
    item: Item = models.ForeignKey(Item, on_delete=models.PROTECT)

    def __str__(self):
        return '{}-[{}]'.format(self.entry, self.item.epc)

    class Meta:
        db_table = 'warehouse_entry_item'
        unique_together = ('entry', 'item')

templates/dashboard/logistics/transfers/transfer_order_detail.html
{% extends "dashboard/dashboard_base.html" %}
{% load django_tables2 %}
{% load static %}
{% block child %}
<main class="c-main">
    <div class="container-fluid">
        <div class="fade-in">

            <div class="row ow-eq-height">
                <div class="col-md-8">
                    <div class="card card-accent-info">
                        <div class="card-header h3"><strong>Pedido:  {{order_object.pk}}</strong></div>
                        <div class="card-body">
                            <div>
                                <strong> Destino </strong> : {{order_object.destination }}
                            </div>
                            <div>
                                <strong> Fecha esperada de entrega </strong> : {{ order_object.expected_completion_date }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 h-100">
                    <div class="card h-100 card-accent-info">
                        <div class="card-body">
                            <div class="text-value-lg"><h2>{{enlisted_items_per}} %</h2></div><small class="text-muted text-uppercase font-weight-bold"> Items alistados ({{enlisted_items_count}})</small>
                            <div class="progress progress-xs mt-3 mb-0">
                            <div class="progress-bar bg-gradient-warning" role="progressbar" style="width: {{enlisted_items_per}}%" aria-valuenow="{{enlisted_items_per}}" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- /.row-->
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-accent-info">
                        <div class="card-header h4 mb-0">
                        Items ({{items_count}})
                        </div>
                        <div class="card-body p-0">
                        {% render_table table %}
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row-->
        </div>
  </div>
</main>
{% endblock %}

templates/dashboard/logistics/transfers/transfer_order_list.html
{% extends "dashboard/dashboard_base.html" %}
{% load django_tables2 %}
{% load static %}
{% block child %}
{% load widget_tweaks %}
<main class="c-main">
    <div class="container-fluid">
        <div class="fade-in">
            <div class="row">
                <div class="col-9 col-lg-10"></div>
                <div class="col-3 col-lg-2">
                    <div class="form-group mx-4 d-inline-block">
                        <input id="create" class="btn btn-info" type="button"
                               data-bs-toggle="modal" data-bs-target="#create_transfer_order"
                               data-popup-url='{% url "warehouse:create_transfer_order" %}'
                               value="Crear Orden"
                        />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-lg-4">
                    <div class="card overflow-hidden">
                        <div class="card-body p-0 d-flex align-items-center">
                            <div class="bg-gradient-dark p-4 mfe-3">
                                <svg class="c-icon c-icon-xl">
                                <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-qr-code"></use>
                                </svg>
                            </div>
                            <div>
                                <div class="text-value text-info">{{total_orders}}</div>
                                <div class="text-muted text-uppercase font-weight-bold small">Total salidas</div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.col-->
                <div class="col-6 col-lg-4">
                    <div class="card overflow-hidden">
                        <div class="card-body p-0 d-flex align-items-center">
                            <div class="bg-gradient-success p-4 mfe-3">
                                <svg class="c-icon c-icon-xl">
                                <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-house"></use>
                                </svg>
                            </div>
                            <div>
                                <div class="text-value text-info">{{total_completed_orders}}</div>
                                <div class="text-muted text-uppercase font-weight-bold small">Salidas completadas</div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.col-->
                <div class="col-6 col-lg-4">
                    <div class="card overflow-hidden">
                        <div class="card-body p-0 d-flex align-items-center">
                            <div class="bg-gradient-warning p-4 mfe-3">
                                <svg class="c-icon c-icon-xl">
                                <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-av-timer"></use>
                                </svg>
                            </div>
                            <div>
                                <div class="text-value text-info">{{total_inprogress_orders}}</div>
                                <div class="text-muted text-uppercase font-weight-bold small">Salidas en alistamiento</div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.col-->
            </div>

            <!-- /.row-->
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        {% if filter  %}
                        <div class="card-body">
                            <form action="" method="get" class="form form-inline">
                                <div class="col-12">
                                    <div class="form-group mx-4 mb-2 d-inline-block">
                                        <label for="id_completion_date_min" class="mr-2">Desde</label>
                                        <input type="date" name="completion_date_min"  id="id_completion_date_min" class="form-control">
                                    </div>

                                    <div class="form-group mx-4 mb-2 d-inline-block">
                                        <label for="id_completion_date_max" class="mr-2">Hasta</label>
                                        <input type="date" name="completion_date_max"  id="id_completion_date_max" class="form-control">
                                    </div>

                                    <div class="form-group mx-4 d-inline-block">
                                        <label for="id_destination" class="mr-2">Bodega Destino</label>
                                         {{ filter.form.destination|add_class:"form-control info" }}
                                    </div>
                                    <div class="form-group mx-4 d-inline-block">
                                        <input class="btn btn-info" type="submit" value="Filtrar"/>
                                    </div>
                                </div>
                            </form>
                        </div>
                        {% endif %}
                        <div class="card-body p-0">
                            {% render_table table %}
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row-->
        </div>
  </div>
</main>
{% endblock %}
{% block load_after %}
<script>
  $(document).ready(function(){
    $(document).on("click", "#create", function (e) {
        e.preventDefault();
        var $popup = $("#create_transfer_order");
        var popup_url = $(this).data("popup-url");
        $(".modal-body", $popup).load(popup_url, function () {
          $popup.modal({show: true})
        });
    });
  })
</script>
{% include "dashboard/logistics/transfers/modals/transfer_order.html" %}
{% endblock %}

templates/dashboard/logistics/transfers/warehouse_entry_detail.html
{% extends "dashboard/dashboard_base.html" %}
{% load django_tables2 %}
{% load static %}
{% block child %}
<main class="c-main">
    <div class="container-fluid">
        <div class="fade-in">

            <div class="row ow-eq-height">
                <div class="col-md-12">
                    <div class="card card-accent-info">
                        <div class="card-header"><strong>Entrada de bodega: {{entry_object.pk}}</strong></div>
                        <div class="card-body">
                            <div>
                                <strong> Origen </strong> : {{entry_object.origin }}
                            </div>
                            <div>
                                <strong> Fecha de recepción </strong> : {{ entry_object.entry_date }}
                            </div>
                            <div>
                                <strong> Bodega de recepción </strong> : {{ entry_object.location }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- /.row-->
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body p-0">
                        {% render_table table %}
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row-->
        </div>
  </div>
</main>
{% endblock %}

templates/dashboard/logistics/transfers/warehouse_entry_list.html
{% extends "dashboard/dashboard_base.html" %}
{% load django_tables2 %}
{% load static %}
{% block child %}
{% load widget_tweaks %}
<main class="c-main">
    <div class="container-fluid">
        <div class="fade-in">
            <div class="row">
                <div class="col-6 col-lg-6">
                    <div class="card overflow-hidden">
                        <div class="card-body p-0 d-flex align-items-center">
                            <div class="bg-gradient-dark p-4 mfe-3">
                                <svg class="c-icon c-icon-xl">
                                <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-qr-code"></use>
                                </svg>
                            </div>
                            <div>
                                <div class="text-value text-info">{{total_items_today}}</div>
                                <div class="text-muted text-uppercase font-weight-bold small">Total items recibidos hoy </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.col-->
                <div class="col-6 col-lg-6">
                    <div class="card overflow-hidden">
                        <div class="card-body p-0 d-flex align-items-center">
                            <div class="bg-gradient-success p-4 mfe-3">
                                <svg class="c-icon c-icon-xl">
                                <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-qr-code"></use>
                                </svg>
                            </div>
                            <div>
                                <div class="text-value text-info">{{total_sku_today}}</div>
                                <div class="text-muted text-uppercase font-weight-bold small">Total referencias recibidas hoy</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- /.row-->
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        {% if filter  %}
                        <div class="card-body">
                            <form action="" method="get" class="form form-inline">

                                <div class="col-12">
                                    <div class="form-group mx-4 mb-2 d-inline-block">
                                        <label for="id_entry_date_min" class="mr-2">Desde</label>
                                        <input type="date" name="entry_date_min"  id="id_entry_date_min" class="form-control">
                                    </div>

                                    <div class="form-group mx-4 mb-2 d-inline-block">
                                        <label for="id_entry_date_max" class="mr-2">Hasta</label>
                                        <input type="date" name="entry_date_max"  id="id_entry_date_max" class="form-control">
                                    </div>
                                    <div class="form-group mx-4 d-inline-block">
                                        <label for="id_location" class="mr-2">Bodega origen</label>
                                         {{ filter.form.origin|add_class:"form-control info" }}
                                    </div>
                                    <div class="form-group mx-4 d-inline-block">
                                        <label for="id_origin" class="mr-2">Bodega Recepción</label>
                                         {{ filter.form.location|add_class:"form-control info" }}
                                    </div>
                                    <div class="form-group mx-4 d-inline-block">
                                        <input class="btn btn-info" type="submit" value="Filtrar"/>
                                    </div>
                                </div>
                            </form>
                        </div>
                       {% endif %}
                        <div class="card-body p-0">
                        {% render_table table %}
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row-->
        </div>
  </div>
</main>
{% endblock %}