principal/urls.py
"""principal URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from iot import views as iot_views
from rfid import views as rfid_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', iot_views.DashboardView.as_view(), name='index'),

    # URLS LOGISTICS (Include rfid.urls)

    path('rfid/', include(('rfid.urls', 'rfid'), namespace='rfid')),
    path('inventory/', include(('inventory.urls', 'inventory'), namespace='inventory')),
    path('warehouse/', include(('warehouse.urls', 'warehouse'), namespace='warehouse')),
    path('reports/', include(('reports.urls', 'reports'), namespace='reports')),

    # REST API URL (Include rest_api.url)

    path('api/', include(('rest_api.urls', 'rest_api'), namespace='rest_api')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rest_api/urls.py
"""Rest API Urls"""
from django.urls import path
from . import function_views as rfid_func_views
from rfid.views import ReadersListView, ReadingsListView

urlpatterns = [
    path('readers/', ReadersListView.as_view(), name='rfid-reader-list'),
    path('readings/', ReadingsListView.as_view(), name='rfid-readings-list'),
    path('reading-zones-snapshot/', rfid_func_views.reading_zones_summary, name='reading-zones-snapshot'),
    path('transfer-order-coordinates/', rfid_func_views.transfer_order_coordinates,
         name='transfer-order-coordinates'),
    path('reading-missing-items/', rfid_func_views.missing_items_readings, name='reading-missing-items'),
    path('items-movements/', rfid_func_views.item_movements, name='items-movements'),
    path('readings/zebra/', rfid_func_views.test_rfid_readings, name='readings-zebra')
]

rfid/urls.py
"""RFID App Urls"""

from django.urls import path
from . import views as rfid_views

urlpatterns = [
    path('readers/', rfid_views.ReadersListView.as_view(), name='rfid-readers'),
    path('readings/', rfid_views.ReadingsListView.as_view(), name='rfid-readings')
]

templates/dashboard/logistics/tracking/tracking_transfer_orders.html
{% extends "dashboard/dashboard_base.html" %}
{% load django_tables2 %}
{% load static %}
{% block child %}
<main class="c-main">
    <div class="container-fluid">
        <div class="fade-in">
            <div class="row mb-2">
                <div class="col-md-9 pr-0">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Número de Pedido" id="transferIdField">
                    </div>
                </div>
                <div class="col-md-3 pl-0">
                    <div class="input-group">
                        <button class="form-control bg-success text-white" onclick="searchTransfer()">Buscar</button>
                        <button class="form-control bg-info text-white" onclick="searchTransferPath()">Ver ruta</button>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 col-md-12">
                    <div class="card card-accent-info">
                        <div class="card-header  h4 mb-0">Tracking</div>
                        <div class="card-body h-100 p-0" >
                                <div id="map" style="height: 500px;"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
  </div>
</main>
{% endblock %}
{% block load_after %}
<script>
let intervals = []
mapboxgl.accessToken = 'pk.eyJ1IjoiaW90LW1pY3JvbGluayIsImEiOiJjazhnM3E5aGkwMHR2M2ZveWNwaWtkbDk0In0.LeF42aYO6fPwmo4RN6YYsg';
let map = new mapboxgl.Map({
container: 'map',
style: 'mapbox://styles/mapbox/streets-v11',
zoom: 14,
center: [-74.1417202, 4.7488383],
});

let size = 100;

// implementation of CustomLayerInterface to draw a pulsing dot icon on the map
// see https://docs.mapbox.com/mapbox-gl-js/api/#customlayerinterface for more info
let pulsingDotRed = {
    width: size,
    height: size,
    data: new Uint8Array(size * size * 4),

    // get rendering context for the map canvas when layer is added to the map
    onAdd: function() {
        var canvas = document.createElement('canvas');
        canvas.width = this.width;
        canvas.height = this.height;
        this.context = canvas.getContext('2d');
    },

    // called once before every frame where the icon will be used
    render: function() {
        var duration = 1000;
        var t = (performance.now() % duration) / duration;

        var radius = (size / 2) * 0.3;
        var outerRadius = (size / 2) * 0.7 * t + radius;
        var context = this.context;

        // draw outer circle
        context.clearRect(0, 0, this.width, this.height);
        context.beginPath();
        context.arc(
            this.width / 2,
            this.height / 2,
            outerRadius,
            0,
            Math.PI * 2
        );
        context.fillStyle = 'rgba(255, 200, 200,' + (1 - t) + ')';
        context.fill();

        // draw inner circle
        context.beginPath();
        context.arc(
            this.width / 2,
            this.height / 2,
            radius,
            0,
            Math.PI * 2
        );
        context.fillStyle = 'rgba(255, 100, 100, 1)';
        context.strokeStyle = 'white';
        context.lineWidth = 2 + 4 * (1 - t);
        context.fill();
        context.stroke();

        // update this image's data with data from the canvas
        this.data = context.getImageData(
            0,
            0,
            this.width,
            this.height
        ).data;

        // continuously repaint the map, resulting in the smooth animation of the dot
        map.triggerRepaint();

        // return `true` to let the map know that the image was updated
        return true;
    }
};

let pulsingDotBlue = {
    width: size,
    height: size,
    data: new Uint8Array(size * size * 4),

    // get rendering context for the map canvas when layer is added to the map
    onAdd: function() {
        var canvas = document.createElement('canvas');
        canvas.width = this.width;
        canvas.height = this.height;
        this.context = canvas.getContext('2d');
    },

    // called once before every frame where the icon will be used
    render: function() {
        var duration = 1000;
        var t = (performance.now() % duration) / duration;

        var radius = (size / 2) * 0.3;
        var outerRadius = (size / 2) * 0.7 * t + radius;
        var context = this.context;

        // draw outer circle
        context.clearRect(0, 0, this.width, this.height);
        context.beginPath();
        context.arc(
            this.width / 2,
            this.height / 2,
            outerRadius,
            0,
            Math.PI * 2
        );
        context.fillStyle = 'rgba(255, 200, 200,' + (1 - t) + ')';
        context.fill();

        // draw inner circle
        context.beginPath();
        context.arc(
            this.width / 2,
            this.height / 2,
            radius,
            0,
            Math.PI * 2
        );
        context.fillStyle = 'rgb(0,114,255)';
        context.strokeStyle = 'white';
        context.lineWidth = 2 + 4 * (1 - t);
        context.fill();
        context.stroke();

        // update this image's data with data from the canvas
        this.data = context.getImageData(
            0,
            0,
            this.width,
            this.height
        ).data;

        // continuously repaint the map, resulting in the smooth animation of the dot
        map.triggerRepaint();

        // return `true` to let the map know that the image was updated
        return true;
    }
};


map.on('load', function() {
    map.addImage('pulsing-dot-home', pulsingDotRed, {
        pixelRatio: 2
    });
    map.addImage('pulsing-dot-transfer', pulsingDotBlue, {
        pixelRatio: 2
    });


    map.addSource('home', {
        'type': 'geojson',
        'data': {
            'type': 'FeatureCollection',
            'features': [{
                'type': 'Feature',
                'geometry': {
                    'type': 'Point',
                    'coordinates': [-74.1417202, 4.7488383]
                }
            }]
        }
    });

    map.addLayer({
        'id': 'points',
        'type': 'symbol',
        'source': 'home',
        'layout': {
            'icon-image': 'pulsing-dot-home'
        }
    });
});

function displayTransfer(data) {

    if (map.getSource('current-transfer-source')){
        map.getSource('current-transfer-source').setData(data);
    }else{
        map.addSource('current-transfer-source', { type: 'geojson', data: data });
        map.addLayer({
            'id': 'current-transfer-layer',
            'type': 'symbol',
            'source': 'current-transfer-source',
            'layout': {
            'icon-image': 'pulsing-dot-transfer'
            }
        });
    }

    map.easeTo(
        {center:data.geometry.coordinates}
    )
}

function resetMap() {
    if (map.getLayer('current-transfer-layer')) map.removeLayer('current-transfer-layer');
    if (map.getSource('current-transfer-source')) map.removeSource('current-transfer-source');
    if (map.getLayer('trace')) map.removeLayer('trace');
    if (map.getSource('trace')) map.getSource('trace');
    intervals.forEach(clearInterval);
    map.easeTo(
        {center:[-74.1417202, 4.7488383]}
    )
}


function searchTransfer() {
    resetMap()
    let searchValue = $("#transferIdField").val().trim();
    let url = "{% url 'rest_api:transfer-order-coordinates' %}?transfer_order_id="+searchValue;
    if (searchValue){

     let timer = window.setInterval(
            function() {
                 $.ajax({
                    url:url,
                    dataType: 'json',
                    success: function( json ) {
                      displayTransfer(json)
                    },
                    error:function() {
                        alert("Pedido no encontrado");
                        window.clearInterval(timer);
                        resetMap();
                    }
                 });
            }, 3000);
     intervals.push(timer)

    }else{
        console.log("no hay valor");
        resetMap();
    }
  
}


function searchTransferPath() {
    resetMap();
    let searchValue = $("#transferIdField").val().trim();
    let url = "{% url 'rest_api:transfer-order-coordinates' %}?include_history=on&transfer_order_id="+searchValue;
    //let url = "https://docs.mapbox.com/mapbox-gl-js/assets/hike.geojson"
    if (searchValue){
         $.ajax({
            url:url,
            dataType: 'json',
            success: function( json ) {
              displayTransferPath(json)
            },
            error:function() {
                alert("Pedido no encontrado");
                window.clearInterval(timer);
                resetMap();
            }
         });
    }else{
        console.log("no hay valor");
        resetMap();
    }

}


function displayTransferPath(data) {


    // save full coordinate list for later
    var coordinates = data.features[0].geometry.coordinates;
    // start by showing just the first coordinate
    data.features[0].geometry.coordinates = [coordinates[0]];
    // add it to the map
    map.addSource('trace', { type: 'geojson', data: data });
    map.addLayer({
        'id': 'trace',
        'type': 'line',
        'source': 'trace',
        'paint': {
        'line-color': 'blue',
        'line-opacity': 0.75,
        'line-width': 5
    }
    });
    // setup the viewport
    map.jumpTo({ 'center': coordinates[0], 'zoom': 14 });

    // on a regular basis, add more coordinates from the saved list and update the map
    var i = 0;
    var timerPath = window.setInterval(function() {
        if (i < coordinates.length) {
        data.features[0].geometry.coordinates.push(
        coordinates[i]
        );
        map.getSource('trace').setData(data);
        map.panTo(coordinates[i]);
        i++;
        } else {
        window.clearInterval(timerPath);
        }
    }, 100);
    intervals.push(timerPath)


}

</script>

{% endblock %}

templates/dashboard/logistics/tracking/tracking_warehouse.html
{% extends "dashboard/dashboard_base.html" %}
{% load django_tables2 %}
{% load static %}
{% block child %}
<main class="c-main">
    <div class="container-fluid">
        <div class="fade-in">
            <div style="width: 700px" class="d-inline-block mr-4">
                <div class="card card-accent-info">
                    <div class="card-header h4 mb-0">Tracking bodega</div>
                    <div class="card-body" >
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                            <a class="nav-link active" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="true">Plano</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="false">Panorámica</a>
                            </li>
                        </ul>
                        <div class="tab-content" id="pills-tabContent">
                            <div class="tab-pane fade show active" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                                <div id="canvas-container-floor">
                                   <canvas id="canvas-floor" height="500px" width="650px"></canvas>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                                <div id="canvas-container">
                                   <canvas id="canvas" height="500px" width="650px"></canvas>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div style="width: calc(100% - 750px)" class="d-inline-block">
                <div class="card card-accent-info">
                    <div class="card-header  h4 mb-0">Resumen</div>
                    <div class="card-body p-0" >
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="border-0 pt-0">Posición</th>
                                    <th class="border-0 pt-0">Cantidad</th>
                                </tr>
                            </thead>
                        {%for row in reading_summary_snapshot %}
                            <tbody id="readings-table" class="font-sm">
                                <tr>
                                    <td>{{row.position__name}}</td>
                                    <td id="totalId{{row.antenna}}">{{row.total}}</td>
                                </tr>
                            </tbody>
                        {%endfor%}
                        </table>
                    </div>
                    <div class="card-header h4 mb-0 border-top">No Encontrados</div> <!-- No Encontrados -->
                    <div class="card-body p-0">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="border-0 pt-0">Serial</th>
                                    <th class="border-0 pt-0">Posición</th>
                                </tr>
                            </thead>
                            <tbody id="missingItemsTable" class="font-sm">
                                <!--- Items injected by jquery -->
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card-header h4 mb-0 border-top">Movimientos</div>
                    <div class="card-body p-0">
                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Item</th>
                                    <th>Última posición</th>
                                    <th>Posición Actual</th>
                                </tr>
                            </thead>
                            <tbody id="itemsMovements" class="font-sm"><!-- items movements --></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
  </div>
</main>
{% endblock %}
{% block load_after %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.6.2/fabric.js"></script>
<script>

let canvas = new fabric.Canvas('canvas');
let canvasFloor = new fabric.Canvas('canvas-floor');

fabric.Image.fromURL('{% static "assets/img/backgrounds/bg_floor.png" %}', function(img){
   img.scaleToWidth(canvasFloor.width);
   img.scaleToHeight(canvasFloor.height);
   canvasFloor.setBackgroundImage(img);
   canvasFloor.requestRenderAll();
});

fabric.Image.fromURL('{% static "assets/img/backgrounds/bodega1.jpeg" %}', function(img){
   img.scaleToWidth(canvas.width);
   img.scaleToHeight(canvas.height);
   canvas.setBackgroundImage(img);
   canvas.requestRenderAll();
});

function paintInitialPolygons(){
  polys = {
      zones : [
          {
              name:1,
              points:[{x: 600, y: 130},{x: 600, y: 560},{x: 275, y: 430},{x: 275, y: 190}]
          },
          {
              name:3,
              points:[{x: 150, y: 210},{x: 148, y: 375},{x: 275, y: 428},{x: 275, y: 188}]
          },
      ]
  }


  polyColors =["rgba(21,232,91,0.1)","rgba(10,0,255,0.1)"];
  polyStrokeColors =["rgba(21,232,91,1)","rgb(7,7,255)"]

  texts = ["0 tags", "0 tags"]
  texts_loc = [{x: 415, y: 300},{x: 210, y: 290}];


  for (let i = 0; polys.zones.length > i; i++){

    window["polygon_" + polys.zones[i].name] = new fabric.Polygon(polys.zones[i].points, { //creates the actual polygon
      fill: polyColors[i],
      PolygonNumber: i,
      name: "Polygon",
      selectable: false,
      objectCaching: false,
      stroke: polyStrokeColors[i],
    });
    window["zoneRFID" + polys.zones[i].name] = new fabric.Text(texts[i], {
        fontFamily: 'Arial',
        fontSize: 30,
        textAlign: 'center',
        originX: 'center',
        originY: 'center',
        stroke: 'black',
        left: texts_loc[i].x,
        top: texts_loc[i].y,
        fill:'white'
    });

    window["group" + i] = new fabric.Group([window["polygon_" + polys.zones[i].name], window["zoneRFID" + polys.zones[i].name] ],{
       selectable: false,
    });
    canvas.add(window["group" + i]);
    canvas.renderAll();


  }

  polys_floor = {
      zones : [
          {
              name:1,
              points:[{x: 240, y: 290},{x: 335, y: 290},{x: 340, y: 150},{x: 235, y: 150}]
          },
          {
              name:3,
              points:[{x: 125, y: 290},{x: 222, y: 290},{x: 227, y: 150},{x: 120, y: 150}]
          },
      ]
  };
  texts_floor_loc = [{x: 289, y: 250},{x: 174, y: 250}];

  for (var i = 0; polys_floor.zones.length > i; i++){

    window["polygonFloor" + polys_floor.zones[i].name] = new fabric.Polygon(polys_floor.zones[i].points, { //creates the actual polygon
      fill: polyColors[i],
      PolygonNumber: i,
      name: "Polygon",
      selectable: false,
      objectCaching: false,
      stroke: polyStrokeColors[i],
    });
    window["zoneRFIDFloor" + polys_floor.zones[i].name ] = new fabric.Text(texts[i], {
        fontFamily: 'Arial',
        fontSize: 30,
        textAlign: 'center',
        originX: 'center',
        originY: 'center',
        stroke: 'blue',
        left: texts_floor_loc[i].x,
        top: texts_floor_loc[i].y,
        fill:'black'
    });

    window["groupFloor" + i] = new fabric.Group(
        [window["polygonFloor"+ polys_floor.zones[i].name],
         window["zoneRFIDFloor" + polys_floor.zones[i].name]],{
       selectable: false,
    });
    canvasFloor.add(window["groupFloor" + i]);
    canvasFloor.renderAll();
    }

}

function updatePolygon(antenna, total){
    document.getElementById('totalId'+(antenna)).innerHTML = total
    window["zoneRFID" + (antenna)].set('text',(total+ " tags"));
    window["zoneRFIDFloor" + (antenna)].set('text',(total+ " tags"));
    canvasFloor.requestRenderAll();
    canvas.requestRenderAll();
}

function fetchAndUpdateData(){

    $.getJSON( '{% url "rest_api:reading-zones-snapshot" %}', function( data ) {
      var items = data.data;
      $.each( items, function( index, val ) {
          $("#totalId"+(val.antenna)).html(val.total);
          updatePolygon(val.antenna, val.total)
      });
    });

    $.getJSON( '{% url "rest_api:reading-missing-items" %}', function( data ) {
    var items = data.data;
    $('#missingItemsTable').empty();
    $.each( items, function( index, val ) {
       $('#missingItemsTable').append(
           '<tr>' +
            '<td>'+ val.sku+ '<br/>' + val.serial + '</td> ' +
            '<td>'+ val.position_name +'</td>' +
           '</tr>'
       )});
    });
    $.getJSON( '{% url "rest_api:items-movements" %}', function( data ) {
    var items = data;
    $('#itemsMovements').empty();
    $.each( items, function( index, val ) {
        $('#itemsMovements').append(
            '<tr>' +
                '<td>'+ val.epc+ '<br/>' + val.display_name + '</td> ' +
                '<td>'+ val.last_seen_position +'</td>' +
                '<td>'+ val.current_position + '</td>' +
            '</tr>'
        );
    });
    });
}

setTimeout(paintInitialPolygons,1000)

setInterval(fetchAndUpdateData,1100)
</script>
{% endblock %}