inventory/urls.py
from django.urls import path

from inventory import views

urlpatterns = [
    path('', views.ItemListView.as_view(), name='item-inventory'),
    path('sku/', views.SKUInventoryView.as_view(),
         name='inventory-sku'),
    path('items-inventory-location/', views.LocationInventoryView.as_view(),
         name='item-inventory-location'),
    path('<int:pk>/sku_detail/', views.SKUDetailView.as_view(), name='sku_detail'),

    path('<str:pk>/detail/', views.ItemDetailView.as_view(), name='item-detail'),

    # autocompletes
    path('autocomplete/skus/', views.SKUAutocomplete.as_view(), name='sku-autocomplete'),
    path('autocomplete/locations/', views.LocationAutocomplete.as_view(), name='location-autocomplete'),
    path('autocomplete/items', views.ItemAutocomplete.as_view(), name='item-autocomplete')
]

principal/urls.py
"""principal URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from iot import views as iot_views
from rfid import views as rfid_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', iot_views.DashboardView.as_view(), name='index'),

    # URLS LOGISTICS (Include rfid.urls)

    path('rfid/', include(('rfid.urls', 'rfid'), namespace='rfid')),
    path('inventory/', include(('inventory.urls', 'inventory'), namespace='inventory')),
    path('warehouse/', include(('warehouse.urls', 'warehouse'), namespace='warehouse')),
    path('reports/', include(('reports.urls', 'reports'), namespace='reports')),

    # REST API URL (Include rest_api.url)

    path('api/', include(('rest_api.urls', 'rest_api'), namespace='rest_api')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rfid/urls.py
"""RFID App Urls"""

from django.urls import path
from . import views as rfid_views

urlpatterns = [
    path('readers/', rfid_views.ReadersListView.as_view(), name='rfid-readers'),
    path('readings/', rfid_views.ReadingsListView.as_view(), name='rfid-readings')
]

warehouse/urls.py
from django.urls import path
from warehouse import views

urlpatterns = [
    path('transfer-orders/', views.TransferOrderListView.as_view(),
         name='transfer-order-list'),
    path('transfer-orders/create/', views.CreateTransferOrder.as_view(), name='create_transfer_order'),
    path('transfer-orders/<int:id_order>/detail/',
         views.TransferOrderDetailView.as_view(), name='transfer-order-detail'),
    path('entries/', views.WarehouseEntryListView.as_view(),
         name='warehouse-entry-list'),
    path('entries/<int:id_entry>/detail/',
         views.WarehouseEntryDetailView.as_view(), name='warehouse-entry-detail'),
    path('transfer-orders/tracking/', views.TrackingTransfersView.as_view(), name='tracking-transfer-orders'),
    path('tracking/', views.TrackingWarehouseView.as_view(), name='tracking-warehouse'),
]

templates/dashboard/dashboard_base.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show" id="sidebar">
  <div class="c-sidebar-brand d-lg-down-none">
    <a href='{% url "index" %}'>
        <img src="{% static 'assets/img/logo/microlink-new.png' %}" alt="" width="100%">
    </a>
  </div>
  <ul class="c-sidebar-nav ps ps--active-y" data-dropdown-accordion="true">
    <li class="c-sidebar-nav-title">Logística</li>

    <li class="c-sidebar-nav-dropdown">
        <a class="c-sidebar-nav-dropdown-toggle">
            <svg class="c-sidebar-nav-icon">
            <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg'%}#cil-blur"></use>
            </svg>Inventario Físico
        </a>
        <ul class="c-sidebar-nav-dropdown-items">
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{% url 'inventory:item-inventory' %}"> Articulos </a></li>
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{% url 'inventory:inventory-sku' %}"> Referencias </a></li>
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{% url 'inventory:item-inventory-location' %}"> Por Bodega </a></li>
        </ul>
    </li>

    <li class="c-sidebar-nav-dropdown">
        <a class="c-sidebar-nav-dropdown-toggle">
            <svg class="c-sidebar-nav-icon">
                <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-truck"></use>
            </svg> Movimientos
        </a>
        <ul class="c-sidebar-nav-dropdown-items">
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{% url 'warehouse:warehouse-entry-list' %}"> Entradas </a></li>
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{% url 'warehouse:transfer-order-list' %}"> Salidas </a></li>
        </ul>
    </li>

    <li class="c-sidebar-nav-dropdown">
        <a class="c-sidebar-nav-dropdown-toggle">
            <svg class="c-sidebar-nav-icon">
                <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-devices"></use>
            </svg> RFID
        </a>
        <ul class="c-sidebar-nav-dropdown-items">
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{% url 'rfid:rfid-readers' %}"> Readers </a></li>
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{% url 'rfid:rfid-readings' %}"> Lecturas </a></li>
        </ul>
    </li>

  </ul>
  <button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent" data-class="c-sidebar-minimized"></button>
</div>
<!--end sidebar-->
<div class="c-wrapper c-fixed-components">
  <header class="c-header c-header-light c-header-fixed c-header-with-subheader">
    <button class="c-header-toggler c-class-toggler d-lg-none mfe-auto" type="button" data-target="#sidebar" data-class="c-sidebar-show">
      <svg class="c-icon c-icon-lg">
        <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-menu"></use>
      </svg>
    </button><a class="c-header-brand d-lg-none" href="#">
      <svg width="118" height="46" alt="CoreUI Logo">
        <use xlink:href="assets/brand/coreui.svg#full"></use>
      </svg></a>
    <button class="c-header-toggler c-class-toggler mfs-3 d-md-down-none" type="button" data-target="#sidebar" data-class="c-sidebar-lg-show" responsive="true">
      <svg class="c-icon c-icon-lg">
        <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-menu"></use>
      </svg>
    </button>

    <ul class="c-header-nav ml-auto mr-4">
      <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link" href="#">
          <svg class="c-icon">
            <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-bell"></use>
          </svg></a>
      </li>


      <li class="c-header-nav-item dropdown"><a class="c-header-nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          <div class="c-avatar"><img class="c-avatar-img" src="{% static 'assets/img/logo/favicon.png' %}" alt="user@email.com"></div>
        </a>
        <div class="dropdown-menu dropdown-menu-right pt-0">
          <div class="dropdown-header bg-light py-2"><strong>Ajustes</strong></div>

          <a class="dropdown-item" href="#">
            <svg class="c-icon mr-2">
              <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-user"></use>
            </svg> Perfil
          </a>

          <a class="dropdown-item" href="#">
            <svg class="c-icon mr-2">
              <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-settings"></use>
            </svg> Ajustes
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <svg class="c-icon mr-2">
              <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-lock-locked"></use>
            </svg> Cambio contraseña</a><a class="dropdown-item" href="#">

            <svg class="c-icon mr-2">
              <use xlink:href="{% static 'vendor/core-ui/icons/sprites/free.svg' %}#cil-account-logout"></use>
            </svg> Cerrar sesión</a>
        </div>
      </li>
    </ul>
    <div class="c-subheader px-3">
      <!-- Breadcrumb-->
      <ol class="breadcrumb border-0 m-0">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item active">Dashboard</li>
      </ol>
      <!-- Breadcrumb Menu-->
    </div>
  </header>


  <div class="c-body">
    {% block child %}{% endblock %}
  </div>
  <footer class="c-footer">
    <div><a href="https://www.microlink.com.co/" target="_blank">Microlink S.A.S </a> &copy; 2023</div>
    <div class="ml-auto">Powered by&nbsp;<a href="https://www.microlink.com.co/" target="_blank">Microlink SAS</a></div>
  </footer>
</div>
{% endblock %}